version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb1
    ports:
       - 8833:3306
    volumes:
      - ./database/db1:/var/lib/mysql
    env_file:
      .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: admindb1
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
